### ISSUE TITLE
Asset Serialization to ForceText?

### ISSUE THREAD

**Issue by nah0y** [InvexGames/MaterialUI#11]
Hello,

Just wanted to know if in Edit/Project Settings/Editor you had Asset Serialization set to Force Text?
Because it seems that all your prefabs in ComponentPrefabs and the colors such as Editor/01 - Red are binaries (downloading the raw file from github and opening it, we can see that it's binary).

The issue is that opening these in Unity will reserialize everything and git will mark these files as modified :/
If you already have ForceText, maybe it's because I'm working with a different version of Unity? Which one are you using? Thanks!

**Comment by InvexGames** [comment]
I have mine set to 'mixed', and don't seem to get that.

**Comment by InvexGames** [comment]
I've set it to 'force text' now, so hopefully you won't get that problem anymore.

**Comment by nah0y** [comment]
Ah thx! I'm sure this will be better for everybody, force text is much better to merge, compare everything in the project, as it's text and not binary.

You didn't have issue because mine was set to text, so at import Unity was converting them from binary to text.

**Comment by InvexGames** [comment]
Ah, makes sense then.
