### ISSUE TITLE
Demo scene

### ISSUE THREAD

**Issue by nah0y** [InvexGames/MaterialUI#12]
Maybe I'll take some time and try to reproduce every demo there is on this page: https://material.angularjs.org/#/demo/material.components.autocomplete

What do you think?

**Comment by InvexGames** [comment]
That would be awesome, although I think this would be a better reference: https://www.polymer-project.org/components/paper-elements/demo.html#paper-input

**Comment by nah0y** [comment]
The first site is better visually and with functionality, but no problem :)

**Comment by nah0y** [comment]
Just to make sure, don't you think the first site is better?
Look at just the checkboxes :
- https://material.angularjs.org/#/demo/material.components.checkbox
- https://www.polymer-project.org/components/paper-elements/demo.html#paper-checkbox

On the first site, we can clearly see easily which one is deactivated, which one is disabled etc... there is even the text that changes when we click on a checkbox, and the last one show the checkbox without the ripple effect.

Just to make sure :)
Also, I've started working on a first example, and there is something that are not quite fitting what the "real" material design should be. What should I do when it's the case? Open an issue every time?

**Comment by InvexGames** [comment]
Yeah, good points - use the first one if you reckon it's better. Just make sure any colours/measurements etc match [this site](http://www.google.com/design/spec/material-design/introduction.html), as it's the one MaterialUI's based off, and the 'official' spec. If what you're doing/want to know isn't there, just ask me here :)

**Comment by nah0y** [comment]
So !

For the very first demo scene, checkboxes. https://material.angularjs.org/#/demo/material.components.checkbox

It seems that by default when putting a checkbox on the screen, we should not see the gray circle.
In your implementation, we can see the gray circle (we can see in the image below in focused and pressed). By default, we should see nothing.
![image](https://cloud.githubusercontent.com/assets/437308/6393393/f4254858-bdc9-11e4-9a0f-70a6648c9ab1.png)

Also, on the Toggle script, pressing the Is On boolean in the inspector, does not enable the checkbox. Even in play mode. In the basic Unity UI, if you do that in a toggle, even if you're not in play mode, the toggle is selected and the checkbox check appears.

Cheers :)

**Comment by nah0y** [comment]
One another thing I'm trying to do, is change a text.text value with the value of the toggle.
I can't do that in the Toggle OnValueChanged section, because it asks for a string, and I want to give it toggle.isOn.
So I looked at using EZAnim, but when I drop a Text in the Target GameObject, in the Target Variable, there is not the option to set the Text value :(

**Comment by nah0y** [comment]
Another thing about checkbox, it seems according to Google guidelines. That when the box is checked (see my image of checkboxes), the green background should be in front of the black border. And that's not the case in your implementation :)

Are you sure you want me to tell you every detail like that and in a single issue? :)

**Comment by nah0y** [comment]
Another thing about Checkboxes, I don't know how to make a disabled checkbox. A checkbox not clickable and change its color to a disabled color :)
For example, setting Interactable to false on the Toggle script, does not work at all (I think you should check that in your Checkbox script)

**Comment by nah0y** [comment]
Same thing for RadioButtons, the gray circle, setting isOn, disabled state etc...

**Comment by nah0y** [comment]
I've added 2 scenes (checkbox and radio button) to my fork in the feature/demo_scenes branch.
You can take a look (it's not finished because of the issues I've told you) and I'd really love to remove all the ugly code I had to add because events are not like in NGUI :/
If you have time to talk about it, that would be great :p

https://github.com/nah0y/MaterialUI/tree/feature/demo_scenes

**Comment by InvexGames** [comment]
Hey, sorry, just going to bed now, but I'll take a long look at this tomorrow and probably end up redesigning the checkbox to make it work better :)

**Comment by nah0y** [comment]
No problem, see you later ;)

**Comment by InvexGames** [comment]
Just thought I'd let you know I'm reworking the checkbox now. Making it performance-friendly, user-friendly and match the MD spec is trickier than I originally thought. I'm confident it can be done without anything too hacky though :)

**Comment by InvexGames** [comment]
It's a shame there's no way to invert masks, or cut a hole in an image at runtime - a LOT of the components would be better and easier to use if I could do that. Unfortunately I have little to no experience with shaders :/

**Comment by InvexGames** [comment]
Also, I don't mind you telling me every single little issue you find - the more scrutiny and nitpicking MaterialUI goes through, the better it'll be! :)

**Comment by InvexGames** [comment]
Alrighty, I think I've fixed all the issues with the checkbox. It's also much better on performance, and will work on any background without that annoying circle. The text can change depending on the state, as well as the colors. Check it out here: ![Image](http://i.imgur.com/UPNwofl.gif)

The only thing I haven't been able to fix is the toggling of the checkbox when the inspector bool is clicked. I did some testing and worked out that it wasn't an issue with the checkbox, but rather that when you change the toggle value through the inspector, it doesn't send the 'on value changed' message.

**Comment by InvexGames** [comment]
Now to add those features to radiobuttons and switches :)

**Comment by nah0y** [comment]
Nice!
Will try that as soon as I can. But looks nice! :p
I'm curious to see how you handled the text changed when clicked.
And if you don't find how to change the toggle value through inspector I'll try to take a look.

**Comment by InvexGames** [comment]
I used [this script](https://github.com/InvexGames/MaterialUI/blob/master/Scripts/ToggleTextChanger.cs) to change the text - You just attach it to the text and link it to the 'on value changed' on the toggle component in the inspector.

**Comment by nah0y** [comment]
Hum... why not :)
Simple and elegant.

**Comment by InvexGames** [comment]
I usually prefer lots of small scripts doing things very well ;)

**Comment by nah0y** [comment]
I've just played a little bit with it. Really great :)

Some comments:
- How do you make a checkbox disabled? I tried to set interactable to false but it just make it not interactable (but the disbled color is not set)
- When the toggle is not interactable, we can still click on the checkbox and the ripple will appear (it will not check the box, but I would assume the ripple to not show?)
- as I commented in your code, why did you add a bool interactable to the Checkbox Toggler and not use the one in the toggle directly?
- the inspector UI and options you added are perfect :p
- oh also, when we press play, the checkbox will directly animate to the state it has to be. So instead of directly be in the state (checked or not) we will see the animation. And it might be confusing.
Maybe you should set the animation time to 0 at the first init?

Otherwise, really nice! :)

**Comment by nah0y** [comment]
One thing about RadioButtons, in one of the examples, instead of having a text next to the radio button, it's an image (with the CheckBox Toggler script attached).
It works fine, but there is a lot of NullPointer exceptions because the RadioConfig script expect a RadioText Text :) (and sometimes we want an image for example :D)

**Comment by nah0y** [comment]
Hum... one thing you'll need to see, is with the demo scene 02, if you select the first radio button and select add, it will add a new radio button, but in fact, it will copy the first radio button, so it will create it and set it to checked (because you selected the first). In my script I set the toggle to false, but the text color remain.

The thing is I had to duplicate the existing toggle because the methods to create RadioButton are editor only. One thing I can do though, is create an instance and hide it directly when we start the scene.
But maybe we can fix the text color issue so users doing the same thing won't have the issue?

**Comment by nah0y** [comment]
For the Switch component, you might want to add the ToggleTextChanger by default on it (as for Checkbox) :)

**Comment by nah0y** [comment]
Switch component, is there a reason the Image background is gray to begin with and not white?
I think most apps will have a white background?

**Comment by nah0y** [comment]
Switch component, the Change Text Color bool does nothing :)

**Comment by nah0y** [comment]
Switch component, trying to do the Switch (Disable Active). Disable is working (with interactable set to false). But if I press the Is On bool on the toggle, when going into play mode, the switch UI is not to true.

**Comment by nah0y** [comment]
Sliders! :D

- I can't find a correct way to resize the width of a slider
- I think most of the time, we want to display a slider with a label of the left. To show what the slider is for. Maybe you could add a "Slider with label" in the MaterialUI menu creation?
- When I change the position of the RectTransform of a Slider, it does not update the position right away, I have to change the scene, or click outside of the position fields of the inspector window
- Is there a reason the Slider has a HorizontalLayoutGroup attached? Because if we want to add other things under this gameObject, it will be repositioned. (I know I can add component on what I have to stop that, but is this a behavour you want?)
- Better way to change slider color? right now if you want to change the color of the slider, you need to change the color of 3 components, might be better to have that directly on the SliderConfig script?
- When you click on the slider (the huge long bar), it seems like you have to click on the exact bar (2px height) to move the slider to the position you clicked.
- Setting interactable to false, deactivate the slider, but there is no deactivated color, and the slider thumb still grows when we mouse over.

I'll push the Sliders scene so you can play with it while fixing the issues.

**Comment by nah0y** [comment]
If you want, you can close this issue.

**Comment by InvexGames** [comment]
Alrighty, sounds good.
