### ISSUE TITLE
Error On Package Import (0.2.2 And Above)

### ISSUE THREAD

**Issue by DrabWeb** [InvexGames/MaterialUI#13]
When I imported the package, I got this error

`Assets/MaterialUI/Scripts/Components/ButtonConfig.cs(35,31): error CS0723: MaterialUI.ButtonConfig.inkBlotsControl': cannot declare variables of static types`

I tried fixing it multiple ways, but when I actually get it to run, the ink blots don't work. I would be very happy if you could help me, as I love the new features!

Thanks,
DrabWeb

**Comment by InvexGames** [comment]
Hi there! I don't seem to be getting this issue when importing. Would you mind telling me which version of Unity you have, and if any other packages have been imported or if any other assets exist in the project? Maybe try importing it into a blank project and see if that works?

Cheers.

**Comment by DrabWeb** [comment]
Fixed it! Just had to delete all the folders from the old version and import it

**Comment by InvexGames** [comment]
Sweet.
