### ISSUE TITLE
ScreenManager?

### ISSUE THREAD

**Issue by nah0y** [InvexGames/MaterialUI#14]
I'd love to see a demo (gif/video) of what the screen manager does.
I'm sure it's something to easily move from one UI to another, but never saw that in action :)

**Comment by InvexGames** [comment]
https://www.youtube.com/watch?v=Q9Fk6pir4DU&feature=youtu.be :)

**Comment by InvexGames** [comment]
If you're wondering what something does, you can check the wiki to see if it's there. If not, list a wiki entry/tutorial request in the dedicated issue I'm about to make.

**Comment by nah0y** [comment]
Oh, that's because you added that recently, it wasn't there when I check a few days ago ;)
