### ISSUE TITLE
Input Text performance issue

### ISSUE THREAD

**Issue by timnak** [InvexGames/MaterialUI#18]
So I was trying out the text input.
If you try to type something really fast, it'll drop the frame rate to zero and gets stuck for a second or so.

Is this Unity UI's issue or MaterialUI?

**Comment by nah0y** [comment]
Hello.

Why did you close it so fast? Was it a problem on your side?

**Comment by timnak** [comment]
Hey,

I though I deleted it.
Yeah, I bound the F key before to some process intensive script and I forgot.

**Comment by nah0y** [comment]
Hehe good news, thanks!

**Comment by InvexGames** [comment]
That's funny.

However, you're not wrong about there being some performance issues - to get the automatic multiline to work with the builtin text edit component, I had to do it in some pretty horrendous hackish way, which I plan on changing - or at the very least optimising.

**Comment by InvexGames** [comment]
Alrighty, it was the last version that was bad - it's actually pretty good.
