### ISSUE TITLE
Colliders on Switchs too big?

### ISSUE THREAD

**Issue by nah0y** [InvexGames/MaterialUI#25]
Also, one thing really weird, if you have multiple switch, it seems like only one of the switches receives input from the click... And I suspect the shadow being really big, blocking the input of others.
So if you have an inactive switch next to an active one, you won't be able to click on the active one for example because it is blocked by the shadow collider of the inactive one.
Or if you have two active next to each other and click on the first, it's the second who receives the event.

I'll soon push to a branch the example switch scene, you'll see the issue.

**Comment by InvexGames** [comment]
Fixed :)
