### ISSUE TITLE
RadioButtons ToggleGroup is not working

### ISSUE THREAD

**Issue by nah0y** [InvexGames/MaterialUI#26]
We you press play with a Radio Buttons component (with 3 radio buttons), none of them have the link to the ToggleGroup :/

**Comment by nah0y** [comment]
In the RadioConfig script, in OnEnable, you do: 
toggleGroup = gameObject.GetComponent<RectTransform>.GetComponent<ToggleGroup>();

but you have to do:
toggleGroup = gameObject.transform.parent.parent.GetComponent<ToggleGroup>();

**Comment by InvexGames** [comment]
Fixed :)
