### ISSUE TITLE
RadioButton Icon Checkbox Toggler

### ISSUE THREAD

**Issue by nah0y** [InvexGames/MaterialUI#27]
That's really nice that you added an Icon to the RadioButton, Checkbox component etc... (with the text) but I think they need to have the CheckboxToggler script attached to them :)

**Comment by nah0y** [comment]
Also I don't know what to put as default image, but I would have put just a simple rectangular grey image instead of the + icon, no?

**Comment by nah0y** [comment]
Hum... and also, as it has the ColorCopier component, we can't set this image to the color we want (which could be different)

**Comment by InvexGames** [comment]
To pick your own color, you would simply disable the ColorCopier, yeah?

**Comment by nah0y** [comment]
Nope :/
Checkout the demo scenes I've pushed in my pull request if you want to see.

**Comment by InvexGames** [comment]
Hm, it works for me...

**Comment by nah0y** [comment]
Oops sorry, got mixed in the issues... yes working :)

**Comment by InvexGames** [comment]
Sweet.
