### ISSUE TITLE
Issues with sliders

### ISSUE THREAD

**Issue by nah0y** [InvexGames/MaterialUI#31]
Sliders! :D

- I can't find a correct way to resize the width of a slider
- I think most of the time, we want to display a slider with a label of the left. To show what the slider is for. Maybe you could add a "Slider with label" in the MaterialUI menu creation?
- When I change the position of the RectTransform of a Slider, it does not update the position right away, I have to change the scene, or click outside of the position fields of the inspector window
- Is there a reason the Slider has a HorizontalLayoutGroup attached? Because if we want to add other things under this gameObject, it will be repositioned. (I know I can add component on what I have to stop that, but is this a behavour you want?)
- Better way to change slider color? right now if you want to change the color of the slider, you need to change the color of 3 components, might be better to have that directly on the SliderConfig script?
- When you click on the slider (the huge long bar), it seems like you have to click on the exact bar (2px height) to move the slider to the position you clicked.
- Setting interactable to false, deactivate the slider, but there is no deactivated color, and the slider thumb still grows when we mouse over.

I have pushed the Sliders scene so you can play with it while fixing the issues.

**Comment by InvexGames** [comment]
I'll get on it :)

**Comment by InvexGames** [comment]
Fixed with latest commit.

**Comment by nah0y** [comment]
Just wanted to say that this is the best designed component so far :)
The main script attached directly on the Slider gameObject, allowing to control all the aspect of the component, really great ;)
(I'm saying this, because for others such as checkboxes and switches, we have to go inside the Switch gameObject, and then find the script that we're looking for on the Toggle gameObject). If every component could have the main script at the root, that would be way better (just saying :D)

- The resize is perfect, really handy and great.
- Perfect that you added the 3 types of sliders

The only thing still not okay IMO, is when you click on the slider to change the value, the collider is really too small in height, you really need to click on the 2px height bar to register the click, I would have made the collider zone as big as the height of the handle.

Anyway, awesome!
