### ISSUE TITLE
#ERROR# Trying to add UnityEngine.UI.LayoutRebuilder for layout rebuild while we are already inside a layout rebuild loop.

### ISSUE THREAD

**Issue by eliehaykal** [InvexGames/MaterialUI#34]
Hello,

I just imported the package into my unity environment and was greeted with the following error:

Trying to add UnityEngine.UI.LayoutRebuilder for layout rebuild while we are already inside a layout rebuild loop. This is not supported. UnityEngine.Canvas:SendWillRenderCanvases()

Any clues on what might be the problem ?

Thanks,

**Comment by InvexGames** [comment]
Hi,

What version are you using? Are you using any other packages?

**Comment by eliehaykal** [comment]
Hi and sorry for the late reply.

I am running on 4.6.0b17 and I am not using any package. It is a clean project that I am testing on.

Thanks,

**Comment by nah0y** [comment]
I too have some issues with using 4.6.0.
I think the best things to do is start using at least 4.6.2 as the UI tools were improved and you should be good to go ;)

**Comment by eliehaykal** [comment]
Hello nah0y,
I'll give it a shot :)
Thanks

**Comment by InvexGames** [comment]
Hey eliehaykal,

Let me know if you had any luck with that, when you get around to it :)

Cheers!

**Comment by eliehaykal** [comment]
Hello Invex,

Upgrading the unity version appears to have solved the issue. 

Thanks,

**Comment by InvexGames** [comment]
Sweet.
