### ISSUE TITLE
MaterialUI as a Git Submodule

### ISSUE THREAD

**Issue by ATBrackeys** [InvexGames/MaterialUI#4]
Hello there,

Great work on MaterialUI, it's really an awesome extension / graphics library. I'm using it in my own GitHub project and since you are so regularly updating it, I thought I would clone it into my project using a Git Submodule. The issue here is that in doing so, the whole project is copied because git doesn't allow partial syncing of repositories. Therefore I suggest reordering the MaterialUI GitHub to only include the MaterialUI folder (especially now that you've organised everything so neatly inside it). All the other Unity files should be handled by each individual project.

I really hope to see this in a future update, it makes it much easier for people to keep their MaterialUI updated. Keep it up! :+1:

**Comment by InvexGames** [comment]
Hey, just rearranged the repo to allow what you requested (It was good to get it done as I was planning on doing something similar for a while)

**Comment by nah0y** [comment]
Hello!

Just a simple question. How are we supposed to import the project if we want to contribute to it, now that it's a submodule?

Should I fork the submodule and create another github repository that use my fork as a submodule?
