### ISSUE TITLE
Countdown Game - First experiement with this awesome asset

### ISSUE THREAD

**Issue by eliehaykal** [InvexGames/MaterialUI#51]
Hello Devs,
- First, I would like to extend my thanks to both Saxy_Man and ahcookies for the valuable Unity3D Material design package which we took advantage off to create our number puzzle game.
- The asset provides a wide array of controls to use. We then added our own choice of colors to create the overall UI look and feel.
- The game is based on the famous TV Show "CountDown" and the rules are quite simple: build equations from 6 numbers until you find a designated number
- Please do enjoy and we are open for all types of feedback. (Link to the game can be found at the top)
- We are constantly improving the product as necessary and keep up the great work with the package

Thanks,

Link to Playstore: https://play.google.com/store/apps/details?id=com.runjumpfall.sixtoone

**Comment by DecSmith42** [comment]
Hey there,I tried out your game ,lovely stuff! (I was the one who commented on your reddit post)

You can check out some info about our new beta here: https://www.reddit.com/r/Unity3D/comments/3gg7do/introducing_materialui_beta/

P.S: /u/ahcookies was working on a separate package for NGUI, and wasn't actually working with me. Not quite sure if they're still doing that or not.

**Comment by eliehaykal** [comment]
Thanks so much. Will check for sure. Btw, I'll be posting on /r/gamedev very soon so if you feel like popping in and talking about the beta in the thread, that would be awesome. I'll keep you informed.

**Comment by DecSmith42** [comment]
Sweet! Just let us know when you're gonna do that and we'll be sure to
swing by :)
