### ISSUE TITLE
Add Text for ComponentPrefabs

### ISSUE THREAD

**Issue by nah0y** [InvexGames/MaterialUI#6]
Hello,

I've just noticed that there is no single Text component in the prefab and in the MaterialUI menu.
It will be really handy to create a Label just like any other component ;)

**Comment by InvexGames** [comment]
Hey there!

Unless you wanted something specific, you can just create them
![as a normal uGUI text](https://cloud.githubusercontent.com/assets/8607368/6286646/95a6e818-b955-11e4-99da-0fcff05428a5.gif)

**Comment by nah0y** [comment]
Yes of course, but as I use everything under the MaterialUI menu, it would be better if everything was at the same place, so we don't have to look in 200 menus. That's just my opining of course :)

**Comment by InvexGames** [comment]
Sure thing. I might make it default to the Roboto font while I'm at it :)

**Comment by nah0y** [comment]
Yes forgot to tell you that, only for that it's essential :)
